---
  - name: Create work dir
    local_action: file dest="{{ workdir }}" state=directory
    changed_when: False

  - name: Validate existing infrastructure
    local_action: stat path="{{ role_path }}/{{ caname }}.tar"
    register: zipstat
    changed_when: False

  - fail: msg="We need to generate certificates. Please obtain the current copy of CA secrets for this node and place it in {{ role_path }}/{{ caname }}.tar!"
    when: not zipstat.stat.exists

  - name: Extract secrets
    local_action: shell tar -xf {{ role_path }}/{{ caname }}.tar .
    args:
      chdir: "{{ workdir }}"
    changed_when: False

  - name: Check if CA is initialized
    local_action: stat path="{{ workdir }}/pki"
    register: castat
    changed_when: False

  - name: Init PKI
    local_action: command ./easyrsa init-pki chdir="{{ workdir }}"
    when: not castat.stat.exists

  - name: Generate CA certificate
    local_action: command ./easyrsa --batch --req-cn="{{caname}} Ansible local PKI" build-ca nopass chdir="{{ workdir }}"
    when: not castat.stat.exists
