---
  - name: Create work dir
    file: dest="{{ workdir }}" state=directory
    changed_when: False
    delegate_to: "{{ workhost }}"

  - name: Validate existing infrastructure
    stat: path="{{ role_path }}/{{ caname }}.tar"
    register: zipstat
    changed_when: False
    delegate_to: "{{ workhost }}"

  - fail: msg="We need to generate certificates. Please obtain the current copy of CA secrets for this node and place it in {{ role_path }}/{{ caname }}.tar!"
    when: not zipstat.stat.exists

  - name: Extract secrets
    command: tar -xvf "{{ role_path }}/{{ caname }}.tar" -C "{{ workdir }}"
    changed_when: False
    delegate_to: "{{ workhost }}"

  # Don't try to use mode on unarchive. It's incredibly broken
  - name: Fix permissions
    command: chmod -R a+r . chdir="{{ workdir }}"
    delegate_to: "{{ workhost }}"

  - name: Check if CA is initialized
    stat: path="{{ workdir }}/pki"
    register: castat
    changed_when: False
    delegate_to: "{{ workhost }}"

  - name: Init PKI
    command: ./easyrsa init-pki chdir="{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ workhost }}"

  - name: Generate CA certificate
    command: ./easyrsa --batch --req-cn="{{caname}} Ansible local PKI" build-ca nopass chdir="{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ workhost }}"
