---
  - name: Create work dir
    local_action: file dest="{{ workdir }}" state=directory
    changed_when: False

  - name: Validate existing infrastructure
    local_action: stat path="{{ role_path }}/{{ caname }}.tar"
    register: zipstat
    changed_when: False

  - fail: msg="We need to generate certificates. Please obtain the current copy of CA secrets for this node and place it in {{ role_path }}/{{ caname }}.tar!"
    when: not zipstat.stat.exists

  - name: Extract secrets
    local_action: command tar -xvf "{{ role_path }}/{{ caname }}.tar" -C "{{ workdir }}"
    changed_when: False

  # Don't try to use mode on unarchive. It's incredibly broken
  - name: Fix permissions
    local_action: command chmod -R a+r . chdir="{{ workdir }}"

  - name: Check if CA is initialized
    local_action: stat path="{{ workdir }}/pki"
    register: castat
    changed_when: False

  - name: Init PKI
    local_action: command ./easyrsa init-pki chdir="{{ workdir }}"
    when: not castat.stat.exists

  - name: Generate CA certificate
    local_action: command ./easyrsa --batch --req-cn="{{caname}} Ansible local PKI" build-ca nopass chdir="{{ workdir }}"
    when: not castat.stat.exists
