---
  - name: Check if node client certificate exists
    stat: path="{{ workdir }}/pki/issued/{{ansible_nodename}}-{{ client.cn }}.crt"
    register: ccrt
    changed_when: False
    delegate_to: "{{ local_ca_workhost }}"

  - name: Generate client certificate request for this node
    command: ./easyrsa --batch --req-cn="{{client.cn}}" gen-req "{{ansible_nodename}}-{{client.cn}}" nopass chdir="{{ workdir }}"
    when: not ccrt.stat.exists
    delegate_to: "{{ local_ca_workhost }}"

  - name: Generate client certificate for this node
    command: ./easyrsa --batch sign-req client "{{ansible_nodename}}-{{client.cn}}" nopass chdir="{{ workdir }}"
    when: not ccrt.stat.exists
    delegate_to: "{{ local_ca_workhost }}"

  - import_tasks: copy.yml
    vars:
      name: "Client"
      cert: "{{ client }}"
