---
  # Call with variables:
  #
  # * `name`: The name of the files to copy
  # * `src`
  # * `dest`
  # * `tmpname`: Temporary name on the remote host

  - name: Create remote directory
    become: True
    file:
      path: "{{ dest | dirname }}"
      state: directory
      owner: "{{ local_ca_owner }}"
      group: "{{ local_ca_group }}"
      mode: u+rwx

  - name: Copy {{ name }} to node
    become: True
    when: local_ca_is_local
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
      owner: "{{ local_ca_owner }}"
      group: "{{ local_ca_group }}"
      mode: "{{ local_ca_mode }}"

  - name: Fetch {{ name }} to control node
    when: not local_ca_is_local
    fetch:
      src: "{{ src }}"
      dest: "{{ local_ca_fetchdir }}/{{ tmpname }}"
      flat: yes
      validate_checksum: yes
      fail_on_missing: yes
    delegate_to: "{{ local_ca_workhost }}"
    changed_when: False

  - name: Upload {{ name }} to target node
    when: not local_ca_is_local
    become: True
    copy:
      src: "{{ local_ca_fetchdir }}/{{ tmpname }}"
      dest: "{{ dest }}"
      owner: "{{ local_ca_owner }}"
      group: "{{ local_ca_group }}"
      mode: "{{ local_ca_mode }}"
