---
# Call with variables:
#
# * `name`: The name of the files to copy
# * `cert`: The base file name of the certificate to copy

  - name: Copy {{ name }} certificate to node
    become: True
    when: local_ca_is_local
    copy:
      src: "{{ workdir }}/pki/issued/{{ ansible_nodename }}-{{ cert.cn }}.{{ item.key }}"
      dest: "{{ item.value }}"
      owner: "{{ local_ca_owner }}"
      group: "{{ local_ca_group }}"
      mode: "{{ local_ca_mode }}"
    with_dict:
      crt: "{{ cert.cert }}"
      key: "{{ cert.key }}"

  - name: Fetch {{ name }} certificate to control node
    when: not local_ca_is_local
    become: True
    fetch:
      src: "{{ workdir }}/pki/{{ item.value }}/{{ ansible_nodename }}-{{ cert.cn }}.{{ item.key }}"
      dest: "{{ local_ca_fetchdir }}/{{ ansible_nodename }}-{{ cert.cn }}.{{ item.key }}"
      flat: yes
      validate_checksum: yes
      fail_on_missing: yes
    with_dict:
      crt: "issued"
      key: "private"
    delegate_to: "{{ local_ca_workhost }}"

  - name: Upload {{ name }} certificate to target node
    when: not local_ca_is_local
    become: True
    copy:
      src: "{{ local_ca_fetchdir }}/{{ ansible_nodename }}-{{ cert.cn }}.{{ item.key }}"
      dest: "{{ item.value }}"
      owner: "{{ local_ca_owner }}"
      group: "{{ local_ca_group }}"
      mode: "{{ local_ca_mode }}"
    with_dict:
      crt: "{{ cert.cert }}"
      key: "{{ cert.key }}"
