---
  - name: Check if DH parameters exist
    stat: path="{{ workdir }}/{{ ansible_nodename }}-dh.pem"
    register: dhfile
    changed_when: False

  - name: Generate DH parameters
    command: openssl dhparam -outform PEM -out "{{ workdir }}/{{ ansible_nodename }}-dh.pem" {{ lca_dhparam_size }}
    when: not dhfile.stat.exists

  - import_tasks: copy_single.yml
    vars:
      name: "DH parameters"
      src: "{{ workdir }}/{{ansible_nodename}}-dh.pem"
      dest: "{{ dhparam.dest }}"
      tmpname: "dh-{{ ansible_nodename }}.pem"
    when: not dhfile.stat.exists
