---
  - name: Generate DH parameters
    command: openssl dhparam -outform PEM -out {{ workdir }}/{{ ansible_nodename }}-dh.pem {{ local_ca_dhparam_size }}
    args:
      creates: "{{ workdir }}/{{ ansible_nodename }}-dh.pem"
    delegate_to: "{{ local_ca_workhost }}"

  - import_tasks: copy_single.yml
    vars:
      name: "DH parameters"
      src: "{{ workdir }}/{{ ansible_nodename }}-dh.pem"
      dest: "{{ local_ca_dhparam.dest }}"
      tmpname: "dh-{{ ansible_nodename }}.pem"
