---
  - fail: msg="You need to set caname, see README.md"
    when: caname is not defined

  - name: Set work dir
    set_fact:
      workdir: "secrets/pki/{{ caname }}"
    when: lca_is_local

  - name: Set work dir
    set_fact:
      workdir: "{{ lca_basepath }}/{{ caname }}"
    when: not lca_is_local

  - name: Set delegation target
    set_fact:
      workhost: localhost
    when: lca_is_local

  - name: Set delegation target
    set_fact:
      workhost: "{{ lca_hostname }}"
    when: not lca_is_local

  - name: Check if CA is initialized
    stat: path="{{ workdir }}/pki/ca.crt"
    register: castat
    changed_when: False
    delegate_to: "{{ workhost }}"

  - name: Init PKI
    command: ./easyrsa init-pki chdir="{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ workhost }}"

  - name: Generate CA certificate
    command: ./easyrsa --batch --req-cn="{{caname}} Ansible local PKI" build-ca nopass chdir="{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ workhost }}"

  - name: Handle server certificate request
    include_tasks: server.yml
    when: server is defined

  - name: Handle client certificate request
    include_tasks: client.yml
    when: client is defined

  - name: Handle dual certificate request
    include_tasks: both.yml
    when: both is defined

  - name: Handle DH parameters request
    include_tasks: dhparam.yml
    when: dhparam is defined

  - name: Handle ca information request
    include_tasks: ca.yml
    when: ca is defined
