---
  - fail: msg="You need to set caname, see README.md"
    when: local_ca_caname is not defined

  - name: Check local execution
    set_fact:
      local_ca_is_local: "{{ local_ca_workhost == 'localhost' }}"

  - name: Set work dir
    set_fact:
      workdir: "secrets/pki/{{ local_ca_caname }}"
    when: local_ca_is_local

  - name: Set work dir
    set_fact:
      workdir: "{{ local_ca_basepath }}/{{ local_ca_caname }}"
    when: not local_ca_is_local

  - name: Create CA directory
    file:
      name: "{{ workdir }}"
      state: directory
    delegate_to: "{{ local_ca_workhost }}"

  - name: Check if CA is initialized
    stat:
      path: "{{ workdir }}/easyrsa"
    register: castat
    changed_when: False
    delegate_to: "{{ local_ca_workhost }}"

  - name: Copy tar archive
    copy:
      src: ca.template.tar
      dest: "/tmp/easyrsa.tar"
    when: not castat.stat.exists
    delegate_to: "{{ local_ca_workhost }}"

  - name: Extract tar archive
    command: tar xf /tmp/easyrsa.tar -C "{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ local_ca_workhost }}"

  - name: Init PKI
    command: ./easyrsa init-pki chdir="{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ local_ca_workhost }}"

  - name: Generate CA certificate
    command: ./easyrsa --batch --req-cn="{{ local_ca_caname }} Ansible local PKI" build-ca nopass chdir="{{ workdir }}"
    when: not castat.stat.exists
    delegate_to: "{{ local_ca_workhost }}"

  - name: Handle server certificate request
    include_tasks: server.yml
    when: local_ca_server is defined

  - name: Handle client certificate request
    include_tasks: client.yml
    when: local_ca_client is defined

  - name: Handle dual certificate request
    include_tasks: both.yml
    when: local_ca_both is defined

  - name: Handle DH parameters request
    include_tasks: dhparam.yml
    when: local_ca_dhparam is defined

  - name: Handle ca information request
    include_tasks: ca.yml
    when: local_ca_ca is defined
