---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian9
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook-local.yml}
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    #    - dependency
    - syntax
    - create
    - prepare
    - converge
    # At the moment, the idempotence check can't take into account control host
    # state. Therefore, the CA will be recreated (clean copy) and everything will
    # be regenerated, leading to failure
    #    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
      exclude:
        - venv
        - virtenv
