---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure CA is absent
      file:
        path: "secrets/pki/unittest"
        state: absent
      delegate_to: "localhost"

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "secrets"
        - "secrets/pki"
        - "secrets/pki/unittest"
      delegate_to: "localhost"

    - name: Extract template
      shell: tar -xf ../../files/ca.template.tar -C secrets/pki/unittest
      args:
        warn: false
      delegate_to: "localhost"
