---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure CA is absent
      file:
        path: "/tmp/pki/unittest"
        state: absent

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/tmp"
        - "/tmp/pki"
        - "/tmp/pki/unittest"

    - name: Upload template
      copy:
        src: ca.template.tar
        dest: /tmp/pki/ca.template.tar

    - name: Extract template
      shell: tar -xf /tmp/pki/ca.template.tar -C /tmp/pki/unittest
      args:
        warn: false
